import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  users: defineTable({
    email: v.string(),
    password_hash: v.optional(v.string()),
    first_name: v.optional(v.string()),
    last_name: v.optional(v.string()),
    full_name: v.optional(v.string()),
    role: v.union(v.literal("admin"), v.literal("manager"), v.literal("user"), v.literal("super_admin")),
    status: v.union(v.literal("active"), v.literal("inactive"), v.literal("suspended"), v.literal("pending")),
    phone: v.optional(v.string()),
    avatar_url: v.optional(v.string()),
    timezone: v.optional(v.string()),
    language: v.optional(v.string()),
    preferences: v.optional(v.any()),
    permissions: v.optional(v.array(v.string())),
    last_login: v.optional(v.number()),
    login_count: v.optional(v.number()),
    failed_login_attempts: v.optional(v.number()),
    password_reset_token: v.optional(v.string()),
    password_reset_expires: v.optional(v.number()),
    email_verified: v.optional(v.boolean()),
    email_verification_token: v.optional(v.string()),
    two_factor_enabled: v.optional(v.boolean()),
    two_factor_secret: v.optional(v.string()),
    created_at: v.number(),
    updated_at: v.number(),
  }).index("by_email", ["email"]).index("by_status", ["status"]).index("by_role", ["role"]).index("by_created_at", ["created_at"]).index("by_last_login", ["last_login"]),

  clients: defineTable({
    name: v.string(),
    email: v.optional(v.string()),
    phone: v.optional(v.string()),
    address: v.optional(v.string()),
    website: v.optional(v.string()),
    industry: v.optional(v.string()),
    company_size: v.optional(v.union(v.literal("1-10"), v.literal("11-50"), v.literal("51-200"), v.literal("201-500"), v.literal("500+"))),
    status: v.union(v.literal("active"), v.literal("inactive"), v.literal("suspended"), v.literal("trial")),
    subscription_tier: v.union(v.literal("basic"), v.literal("premium"), v.literal("enterprise"), v.literal("custom")),
    billing_address: v.optional(v.string()),
    tax_id: v.optional(v.string()),
    contract_start: v.optional(v.number()),
    contract_end: v.optional(v.number()),
    monthly_spend_limit: v.optional(v.number()),
    total_revenue: v.optional(v.number()),
    logo_url: v.optional(v.string()),
    notes: v.optional(v.string()),
    tags: v.optional(v.array(v.string())),
    created_by: v.id("users"),
    created_at: v.number(),
    updated_at: v.number(),
  }).index("by_status", ["status"]).index("by_created_by", ["created_by"]).index("by_subscription_tier", ["subscription_tier"]).index("by_name", ["name"]).index("by_contract_end", ["contract_end"]),

  members: defineTable({
    user_id: v.optional(v.id("users")),
    client_id: v.optional(v.id("clients")),
    member_id: v.string(),
    first_name: v.optional(v.string()),
    last_name: v.optional(v.string()),
    full_name: v.optional(v.string()),
    email: v.optional(v.string()),
    phone: v.optional(v.string()),
    date_of_birth: v.optional(v.number()),
    gender: v.optional(v.union(v.literal("male"), v.literal("female"), v.literal("other"), v.literal("prefer_not_to_say"))),
    tier: v.union(v.literal("basic"), v.literal("premium"), v.literal("elite"), v.literal("executive")),
    status: v.union(v.literal("active"), v.literal("inactive"), v.literal("pending"), v.literal("suspended"), v.literal("churned")),
    engagement_score: v.optional(v.number()),
    total_spend: v.optional(v.number()),
    lifetime_value: v.optional(v.number()),
    acquisition_channel: v.optional(v.string()),
    acquisition_cost: v.optional(v.number()),
    last_active: v.optional(v.number()),
    location: v.optional(v.string()),
    timezone: v.optional(v.string()),
    language: v.optional(v.string()),
    preferences: v.optional(v.any()),
    tags: v.optional(v.array(v.string())),
    notes: v.optional(v.string()),
    social_profiles: v.optional(v.any()),
    communication_preferences: v.optional(v.any()),
    permissions: v.optional(v.any()),
    referral_code: v.optional(v.string()),
    referred_by: v.optional(v.id("members")),
    created_at: v.number(),
    updated_at: v.number(),
  }).index("by_user", ["user_id"]).index("by_client", ["client_id"]).index("by_member_id", ["member_id"]).index("by_email", ["email"]).index("by_tier", ["tier"]).index("by_status", ["status"]).index("by_engagement_score", ["engagement_score"]).index("by_last_active", ["last_active"]),

  communications: defineTable({
    channel: v.union(v.literal("sms"), v.literal("mms"), v.literal("email"), v.literal("voice"), v.literal("chat"), v.literal("conversation"), v.literal("push"), v.literal("webhook")),
    direction: v.union(v.literal("inbound"), v.literal("outbound")),
    to_number: v.optional(v.string()),
    from_number: v.optional(v.string()),
    to_email: v.optional(v.string()),
    from_email: v.optional(v.string()),
    content: v.string(),
    subject: v.optional(v.string()),
    message_type: v.optional(v.union(v.literal("transactional"), v.literal("marketing"), v.literal("notification"), v.literal("support"))),
    template_id: v.optional(v.string()),
    campaign_id: v.optional(v.id("campaigns")),
    status: v.union(v.literal("queued"), v.literal("sent"), v.literal("delivered"), v.literal("failed"), v.literal("bounced"), v.literal("read"), v.literal("clicked"), v.literal("replied")),
    provider: v.union(v.literal("twilio"), v.literal("sendgrid"), v.literal("other")),
    provider_id: v.optional(v.string()),
    provider_status: v.optional(v.string()),
    provider_response: v.optional(v.any()),
    cost: v.optional(v.number()),
    segments: v.optional(v.number()),
    media_urls: v.optional(v.array(v.string())),
    attachments: v.optional(v.array(v.any())),
    error_message: v.optional(v.string()),
    error_code: v.optional(v.string()),
    retry_count: v.optional(v.number()),
    metadata: v.optional(v.any()),
    client_id: v.optional(v.id("clients")),
    user_id: v.optional(v.id("users")),
    member_id: v.optional(v.id("members")),
    sent_at: v.optional(v.number()),
    delivered_at: v.optional(v.number()),
    read_at: v.optional(v.number()),
    clicked_at: v.optional(v.number()),
    replied_at: v.optional(v.number()),
    created_at: v.number(),
    updated_at: v.number(),
  }).index("by_client", ["client_id"]).index("by_user", ["user_id"]).index("by_member", ["member_id"]).index("by_channel", ["channel"]).index("by_status", ["status"]).index("by_campaign", ["campaign_id"]).index("by_provider", ["provider"]).index("by_sent_at", ["sent_at"]),

  subscriptions: defineTable({
    client_id: v.optional(v.id("clients")),
    user_id: v.optional(v.id("users")),
    member_id: v.optional(v.id("members")),
    subscription_name: v.optional(v.string()),
    plan_name: v.string(),
    plan_type: v.union(v.literal("monthly"), v.literal("yearly"), v.literal("one-time"), v.literal("usage-based")),
    billing_cycle: v.optional(v.union(v.literal("monthly"), v.literal("quarterly"), v.literal("yearly"))),
    amount: v.number(),
    setup_fee: v.optional(v.number()),
    discount_amount: v.optional(v.number()),
    discount_percentage: v.optional(v.number()),
    tax_rate: v.optional(v.number()),
    currency: v.string(),
    status: v.union(v.literal("active"), v.literal("inactive"), v.literal("cancelled"), v.literal("past_due"), v.literal("paused"), v.literal("trial")),
    payment_method: v.optional(v.string()),
    nmi_customer_id: v.optional(v.string()),
    nmi_subscription_id: v.optional(v.string()),
    nmi_plan_id: v.optional(v.string()),
    trial_start_date: v.optional(v.number()),
    trial_end_date: v.optional(v.number()),
    current_period_start: v.optional(v.number()),
    current_period_end: v.optional(v.number()),
    next_billing_date: v.optional(v.number()),
    last_billing_date: v.optional(v.number()),
    cancellation_date: v.optional(v.number()),
    cancellation_reason: v.optional(v.string()),
    auto_renew: v.optional(v.boolean()),
    proration_behavior: v.optional(v.string()),
    metadata: v.optional(v.any()),
    created_at: v.number(),
    updated_at: v.number(),
  }).index("by_client", ["client_id"]).index("by_user", ["user_id"]).index("by_member", ["member_id"]).index("by_status", ["status"]).index("by_nmi_customer", ["nmi_customer_id"]).index("by_next_billing_date", ["next_billing_date"]).index("by_plan_type", ["plan_type"]),

  transactions: defineTable({
    subscription_id: v.optional(v.id("subscriptions")),
    client_id: v.optional(v.id("clients")),
    user_id: v.optional(v.id("users")),
    member_id: v.optional(v.id("members")),
    transaction_id: v.string(),
    nmi_transaction_id: v.optional(v.string()),
    invoice_id: v.optional(v.string()),
    amount: v.number(),
    tax_amount: v.optional(v.number()),
    fee_amount: v.optional(v.number()),
    net_amount: v.optional(v.number()),
    currency: v.string(),
    exchange_rate: v.optional(v.number()),
    type: v.union(v.literal("charge"), v.literal("refund"), v.literal("chargeback"), v.literal("adjustment"), v.literal("credit")),
    status: v.union(v.literal("pending"), v.literal("completed"), v.literal("failed"), v.literal("cancelled"), v.literal("disputed"), v.literal("refunded")),
    payment_method: v.optional(v.string()),
    payment_method_details: v.optional(v.any()),
    gateway_response: v.optional(v.any()),
    authorization_code: v.optional(v.string()),
    reference_number: v.optional(v.string()),
    description: v.optional(v.string()),
    failure_reason: v.optional(v.string()),
    failure_code: v.optional(v.string()),
    risk_score: v.optional(v.number()),
    fraud_details: v.optional(v.any()),
    billing_address: v.optional(v.any()),
    shipping_address: v.optional(v.any()),
    customer_ip: v.optional(v.string()),
    user_agent: v.optional(v.string()),
    metadata: v.optional(v.any()),
    processed_at: v.optional(v.number()),
    settled_at: v.optional(v.number()),
    created_at: v.number(),
    updated_at: v.number(),
  }).index("by_subscription", ["subscription_id"]).index("by_client", ["client_id"]).index("by_transaction_id", ["transaction_id"]).index("by_status", ["status"]).index("by_type", ["type"]).index("by_processed_at", ["processed_at"]).index("by_amount", ["amount"]),

  campaigns: defineTable({
    name: v.string(),
    description: v.optional(v.string()),
    type: v.union(v.literal("sms"), v.literal("email"), v.literal("mixed"), v.literal("voice"), v.literal("push")),
    category: v.optional(v.union(v.literal("marketing"), v.literal("transactional"), v.literal("notification"), v.literal("retention"))),
    status: v.union(v.literal("draft"), v.literal("active"), v.literal("paused"), v.literal("completed"), v.literal("archived")),
    priority: v.optional(v.union(v.literal("low"), v.literal("medium"), v.literal("high"), v.literal("urgent"))),
    target_audience: v.optional(v.any()),
    audience_size: v.optional(v.number()),
    message_template: v.optional(v.string()),
    subject_template: v.optional(v.string()),
    personalization_fields: v.optional(v.array(v.string())),
    schedule_type: v.union(v.literal("immediate"), v.literal("scheduled"), v.literal("recurring"), v.literal("triggered")),
    scheduled_at: v.optional(v.number()),
    recurring_pattern: v.optional(v.string()),
    trigger_conditions: v.optional(v.any()),
    budget: v.optional(v.number()),
    cost_per_message: v.optional(v.number()),
    expected_revenue: v.optional(v.number()),
    conversion_goal: v.optional(v.string()),
    a_b_test_config: v.optional(v.any()),
    tags: v.optional(v.array(v.string())),
    created_by: v.id("users"),
    client_id: v.optional(v.id("clients")),
    launched_at: v.optional(v.number()),
    completed_at: v.optional(v.number()),
    created_at: v.number(),
    updated_at: v.number(),
  }).index("by_status", ["status"]).index("by_created_by", ["created_by"]).index("by_client", ["client_id"]).index("by_type", ["type"]).index("by_scheduled_at", ["scheduled_at"]).index("by_priority", ["priority"]),

  benefits: defineTable({
    name: v.string(),
    description: v.optional(v.string()),
    type: v.union(v.literal("discount"), v.literal("reward"), v.literal("access"), v.literal("service"), v.literal("cashback"), v.literal("points")),
    category: v.optional(v.string()),
    value: v.optional(v.string()),
    value_type: v.optional(v.union(v.literal("percentage"), v.literal("fixed"), v.literal("points"), v.literal("access"))),
    minimum_spend: v.optional(v.number()),
    maximum_usage: v.optional(v.number()),
    usage_period: v.optional(v.union(v.literal("daily"), v.literal("weekly"), v.literal("monthly"), v.literal("yearly"), v.literal("lifetime"))),
    tier_requirement: v.optional(v.union(v.literal("basic"), v.literal("premium"), v.literal("elite"), v.literal("executive"))),
    eligibility_criteria: v.optional(v.any()),
    terms_conditions: v.optional(v.string()),
    start_date: v.optional(v.number()),
    end_date: v.optional(v.number()),
    status: v.union(v.literal("active"), v.literal("inactive"), v.literal("expired"), v.literal("draft")),
    priority: v.optional(v.number()),
    auto_apply: v.optional(v.boolean()),
    stackable: v.optional(v.boolean()),
    client_id: v.optional(v.id("clients")),
    created_by: v.optional(v.id("users")),
    usage_count: v.optional(v.number()),
    redemption_count: v.optional(v.number()),
    created_at: v.number(),
    updated_at: v.number(),
  }).index("by_type", ["type"]).index("by_status", ["status"]).index("by_client", ["client_id"]).index("by_tier_requirement", ["tier_requirement"]).index("by_start_date", ["start_date"]).index("by_end_date", ["end_date"]),

  member_benefits: defineTable({
    member_id: v.id("members"),
    benefit_id: v.id("benefits"),
    status: v.union(v.literal("active"), v.literal("used"), v.literal("expired"), v.literal("revoked")),
    usage_count: v.optional(v.number()),
    remaining_usage: v.optional(v.number()),
    value_redeemed: v.optional(v.number()),
    granted_at: v.number(),
    expires_at: v.optional(v.number()),
    used_at: v.optional(v.number()),
    revoked_at: v.optional(v.number()),
    revocation_reason: v.optional(v.string()),
    granted_by: v.optional(v.id("users")),
    transaction_id: v.optional(v.id("transactions")),
    notes: v.optional(v.string()),
    metadata: v.optional(v.any()),
  }).index("by_member", ["member_id"]).index("by_benefit", ["benefit_id"]).index("by_status", ["status"]).index("by_granted_at", ["granted_at"]).index("by_expires_at", ["expires_at"]),

  analytics: defineTable({
    metric_name: v.string(),
    metric_value: v.number(),
    metric_type: v.union(v.literal("counter"), v.literal("gauge"), v.literal("histogram"), v.literal("timer")),
    metric_unit: v.optional(v.string()),
    dimensions: v.optional(v.any()),
    tags: v.optional(v.array(v.string())),
    source: v.optional(v.string()),
    environment: v.optional(v.union(v.literal("production"), v.literal("staging"), v.literal("development"))),
    client_id: v.optional(v.id("clients")),
    user_id: v.optional(v.id("users")),
    session_id: v.optional(v.string()),
    request_id: v.optional(v.string()),
    correlation_id: v.optional(v.string()),
    metadata: v.optional(v.any()),
    recorded_at: v.number(),
  }).index("by_metric_name", ["metric_name"]).index("by_client", ["client_id"]).index("by_recorded_at", ["recorded_at"]).index("by_metric_type", ["metric_type"]).index("by_source", ["source"]),

  settings: defineTable({
    key: v.string(),
    value: v.any(),
    type: v.union(v.literal("system"), v.literal("client"), v.literal("user"), v.literal("global")),
    data_type: v.optional(v.union(v.literal("string"), v.literal("number"), v.literal("boolean"), v.literal("object"), v.literal("array"))),
    category: v.optional(v.string()),
    description: v.optional(v.string()),
    default_value: v.optional(v.any()),
    validation_rules: v.optional(v.any()),
    is_encrypted: v.optional(v.boolean()),
    is_public: v.optional(v.boolean()),
    requires_restart: v.optional(v.boolean()),
    client_id: v.optional(v.id("clients")),
    user_id: v.optional(v.id("users")),
    environment: v.optional(v.union(v.literal("production"), v.literal("staging"), v.literal("development"))),
    version: v.optional(v.string()),
    last_modified_by: v.optional(v.id("users")),
    created_at: v.number(),
    updated_at: v.number(),
  }).index("by_key", ["key"]).index("by_type", ["type"]).index("by_client", ["client_id"]).index("by_user", ["user_id"]).index("by_category", ["category"]),

  webhooks: defineTable({
    provider: v.string(),
    event_type: v.string(),
    event_id: v.optional(v.string()),
    webhook_id: v.optional(v.string()),
    payload: v.any(),
    headers: v.optional(v.any()),
    signature: v.optional(v.string()),
    signature_verified: v.optional(v.boolean()),
    status: v.union(v.literal("received"), v.literal("processed"), v.literal("failed"), v.literal("ignored"), v.literal("retrying")),
    processing_attempts: v.optional(v.number()),
    max_attempts: v.optional(v.number()),
    next_retry_at: v.optional(v.number()),
    error_message: v.optional(v.string()),
    error_code: v.optional(v.string()),
    processing_time: v.optional(v.number()),
    response_data: v.optional(v.any()),
    client_id: v.optional(v.id("clients")),
    user_id: v.optional(v.id("users")),
    related_entity_type: v.optional(v.string()),
    related_entity_id: v.optional(v.string()),
    source_ip: v.optional(v.string()),
    user_agent: v.optional(v.string()),
    processed_at: v.optional(v.number()),
    created_at: v.number(),
  }).index("by_provider", ["provider"]).index("by_event_type", ["event_type"]).index("by_status", ["status"]).index("by_created_at", ["created_at"]).index("by_processed_at", ["processed_at"]).index("by_client", ["client_id"]),

  conversations: defineTable({
    conversation_sid: v.string(),
    friendly_name: v.optional(v.string()),
    unique_name: v.optional(v.string()),
    chat_service_sid: v.optional(v.string()),
    messaging_service_sid: v.optional(v.string()),
    status: v.union(v.literal("active"), v.literal("inactive"), v.literal("closed"), v.literal("archived")),
    state: v.optional(v.union(v.literal("active"), v.literal("inactive"), v.literal("closed"))),
    participant_count: v.optional(v.number()),
    message_count: v.optional(v.number()),
    media_count: v.optional(v.number()),
    attributes: v.optional(v.any()),
    timers: v.optional(v.any()),
    client_id: v.optional(v.id("clients")),
    member_id: v.optional(v.id("members")),
    user_id: v.optional(v.id("users")),
    campaign_id: v.optional(v.id("campaigns")),
    tags: v.optional(v.array(v.string())),
    priority: v.optional(v.union(v.literal("low"), v.literal("medium"), v.literal("high"), v.literal("urgent"))),
    last_message_at: v.optional(v.number()),
    last_read_message_index: v.optional(v.number()),
    created_at: v.number(),
    updated_at: v.number(),
  }).index("by_conversation_sid", ["conversation_sid"]).index("by_client", ["client_id"]).index("by_member", ["member_id"]).index("by_status", ["status"]).index("by_last_message_at", ["last_message_at"]).index("by_campaign", ["campaign_id"]),

  scheduled_jobs: defineTable({
    campaign_id: v.id("campaigns"),
    job_type: v.union(v.literal("send_message"), v.literal("delay"), v.literal("trigger_event"), v.literal("condition_check"), v.literal("webhook_call")),
    job_name: v.optional(v.string()),
    scheduled_at: v.number(),
    status: v.union(v.literal("pending"), v.literal("running"), v.literal("completed"), v.literal("failed"), v.literal("cancelled"), v.literal("skipped")),
    priority: v.optional(v.union(v.literal("low"), v.literal("medium"), v.literal("high"), v.literal("urgent"))),
    retry_count: v.optional(v.number()),
    max_retries: v.optional(v.number()),
    retry_delay: v.optional(v.number()),
    timeout: v.optional(v.number()),
    payload: v.optional(v.any()),
    result: v.optional(v.any()),
    error_message: v.optional(v.string()),
    error_code: v.optional(v.string()),
    execution_time: v.optional(v.number()),
    dependencies: v.optional(v.array(v.id("scheduled_jobs"))),
    tags: v.optional(v.array(v.string())),
    executed_at: v.optional(v.number()),
    completed_at: v.optional(v.number()),
    created_at: v.number(),
    updated_at: v.number(),
  }).index("by_campaign", ["campaign_id"]).index("by_scheduled_at", ["scheduled_at"]).index("by_status", ["status"]).index("by_job_type", ["job_type"]).index("by_priority", ["priority"]),

  campaign_executions: defineTable({
    campaign_id: v.id("campaigns"),
    execution_type: v.union(v.literal("immediate"), v.literal("scheduled"), v.literal("recurring")),
    target_count: v.optional(v.number()),
    sent_count: v.optional(v.number()),
    failed_count: v.optional(v.number()),
    status: v.union(v.literal("queued"), v.literal("running"), v.literal("completed"), v.literal("failed"), v.literal("paused")),
    started_at: v.optional(v.number()),
    completed_at: v.optional(v.number()),
    error_message: v.optional(v.string()),
    created_at: v.number(),
    updated_at: v.number(),
  }).index("by_campaign", ["campaign_id"]).index("by_status", ["status"]),
});
