name = "echelonx-api"
main = "server/node-build.ts"
compatibility_date = "2024-01-01"
node_compat = true

[env.production]
name = "echelonx-api-production"

[env.staging]
name = "echelonx-api-staging"

[[env.production.vars]]
NODE_ENV = "production"

[[env.staging.vars]]
NODE_ENV = "staging"

[build]
command = "npm run build:server"

[build.upload]
format = "service-worker"
