
export const api = {
  users: {
    getUsers: "users:getUsers",
    getUserById: "users:getUserById", 
    getUserByEmail: "users:getUserByEmail",
    createUser: "users:createUser",
    updateUser: "users:updateUser",
    deleteUser: "users:deleteUser",
    getUserStats: "users:getUserStats",
  },
  members: {
    getMembers: "members:getMembers",
    getMemberById: "members:getMemberById",
    getMemberByMemberId: "members:getMemberByMemberId", 
    getMemberByEmail: "members:getMemberByEmail",
    createMember: "members:createMember",
    updateMember: "members:updateMember",
    deleteMember: "members:deleteMember",
    getMemberStats: "members:getMemberStats",
    updateMemberEngagement: "members:updateMemberEngagement",
    updateMemberSpend: "members:updateMemberSpend",
  },
  clients: {
    getClients: "clients:getClients",
    getClientById: "clients:getClientById",
    createClient: "clients:createClient",
    updateClient: "clients:updateClient",
    deleteClient: "clients:deleteClient",
    getClientStats: "clients:getClientStats",
  },
  communications: {
    getCommunications: "communications:getCommunications",
    getCommunicationById: "communications:getCommunicationById",
    createCommunication: "communications:createCommunication",
    updateCommunicationStatus: "communications:updateCommunicationStatus",
    getCommunicationStats: "communications:getCommunicationStats",
    logSMS: "communications:logSMS",
    logEmail: "communications:logEmail",
  },
  subscriptions: {
    getSubscriptions: "subscriptions:getSubscriptions",
    getSubscriptionById: "subscriptions:getSubscriptionById",
    getSubscriptionByNMICustomer: "subscriptions:getSubscriptionByNMICustomer",
    createSubscription: "subscriptions:createSubscription",
    updateSubscription: "subscriptions:updateSubscription",
    cancelSubscription: "subscriptions:cancelSubscription",
    getSubscriptionStats: "subscriptions:getSubscriptionStats",
    updateSubscriptionBilling: "subscriptions:updateSubscriptionBilling",
  },
  transactions: {
    getTransactions: "transactions:getTransactions",
    getTransactionById: "transactions:getTransactionById",
    getTransactionByTransactionId: "transactions:getTransactionByTransactionId",
    createTransaction: "transactions:createTransaction",
    updateTransactionStatus: "transactions:updateTransactionStatus",
    getTransactionStats: "transactions:getTransactionStats",
    processNMITransaction: "transactions:processNMITransaction",
  },
  campaigns: {
    getCampaigns: "campaigns:getCampaigns",
    getCampaignById: "campaigns:getCampaignById",
    createCampaign: "campaigns:createCampaign",
    updateCampaign: "campaigns:updateCampaign",
    deleteCampaign: "campaigns:deleteCampaign",
    getCampaignStats: "campaigns:getCampaignStats",
    launchCampaign: "campaigns:launchCampaign",
    pauseCampaign: "campaigns:pauseCampaign",
  },
} as const;
