name: Deploy to Cloudflare Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Pages
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
        
      - name: Build application
        run: npm run build:client
        env:
          NODE_ENV: production
          
      - name: Check Cloudflare Credentials
        id: check-credentials
        run: |
          if [ -z "${{ secrets.CLOUDFLARE_API_TOKEN }}" ] || [ -z "${{ secrets.CLOUDFLARE_ACCOUNT_ID }}" ]; then
            echo "credentials-available=false" >> $GITHUB_OUTPUT
            echo "⚠️ Cloudflare deployment skipped - missing credentials"
            echo "To enable Cloudflare Pages deployment, add these secrets to your repository:"
            echo "- CLOUDFLARE_API_TOKEN"
            echo "- CLOUDFLARE_ACCOUNT_ID"
            echo "See CLOUDFLARE_DEPLOYMENT.md for setup instructions"
          else
            echo "credentials-available=true" >> $GITHUB_OUTPUT
            echo "✓ Cloudflare credentials found - proceeding with deployment"
          fi
          
      - name: Deploy to Cloudflare Pages
        if: steps.check-credentials.outputs.credentials-available == 'true'
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: echelonx-platform
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Deploy API to Cloudflare Workers (Optional)
        if: steps.check-credentials.outputs.credentials-available == 'true'
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
